spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devops1?useSSL=false&serverTimezone=Asia/Seoul
    username: zjxmsl
    password: wpDlf@h3dk
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # 개발/테스트용: create / create-drop / update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
