#version: '3'
#services:
#  app:
##    build: .
##    image: ghcr.io/choisangkyou/testbackend:latest  # GHCR 이미지 사용.
#    image: ${GHCR_IMAGE}  # .env 파일에서 이미지 이름을 가져옴.
#    container_name: app-devops1   # 여기서 고정
#    ports:
#      - "${APP_PORT}:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:${DB_PORT}/${MYSQL_DATABASE}
#      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
#      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
#    depends_on:
#      - db
#
#  db:
#    image: mysql:8
#    container_name: db-devops1   # 여기서 고정
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    ports:
#      - "${DB_PORT}:3306"
#    volumes:
#      - db_data:/var/lib/mysql
#
#volumes:
#  db_data:

services:
  app:
    image: ${GHCR_IMAGE:-ghcr.io/choisangkyou/testbackend:latest}
    container_name: testbackend-app
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
      TZ: Asia/Seoul
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${JPA_DDL_AUTO:-update}
      SPRING_JPA_SHOW_SQL: ${JPA_SHOW_SQL:-false}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - testbackend-network
    volumes:
      - app-logs:/app/logs

  db:
    image: mysql:8.0
    container_name: testbackend-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - db-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - testbackend-network

volumes:
  db-data:
  app-logs:

networks:
  testbackend-network:
    driver: bridge